version: '3.8'

networks:
  hospital-network:
    driver: bridge

services:
  # ==========================================
  # 1. BASE DE DATOS CENTRALIZADA
  # ==========================================
  # Un único contenedor MySQL para ahorrar memoria RAM y CPU.
  # Spring Boot creará automáticamente los esquemas lógicos gracias al parámetro 'createDatabaseIfNotExist=true'
  db-hospital:
    image: mysql:8.0
    container_name: hospital-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iha3gaFBMMzwiee8
    ports:
      - "3306:3306"
    networks:
      - hospital-network

  # ==========================================
  # 2. SERVIDOR DE DESCUBRIMIENTO (EUREKA)
  # ==========================================
  ms-eureka:
    build: ./ms-eureka
    container_name: hospital-ms-eureka
    ports:
      - "8761:8761"
    networks:
      - hospital-network

  # ==========================================
  # 3. API GATEWAY
  # ==========================================
  ms-gateway:
    build: ./ms-gateway
    container_name: hospital-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-eureka
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
    networks:
      - hospital-network

  # ==========================================
  # 4. MICROSERVICIOS DE NEGOCIO
  # ==========================================
  ms-auth:
    build: ./ms-auth
    container_name: hospital-ms-auth
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080 # Sobrescribe el puerto interno para evitar conflictos con application.properties
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_auth?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-pacientes:
    build: ./ms-pacientes
    container_name: hospital-ms-pacientes
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_pacientes?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-medicos:
    build: ./ms-medicos
    container_name: hospital-ms-medicos
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_medicos?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-citamedica:
    build: ./ms-citamedica
    container_name: hospital-ms-citamedica
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8084:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_citamedica?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-inventario:
    build: ./ms-inventario
    container_name: hospital-ms-inventario
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8085:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_inventario?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-agenda:
    build: ./ms-agenda
    container_name: hospital-ms-agenda
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8086:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_agenda?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-facturacion:
    build: ./ms-facturacion
    container_name: hospital-ms-facturacion
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8087:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_facturacion?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-historial:
    build: ./ms-historial
    container_name: hospital-ms-historial
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8088:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_historial?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-consultas:
    build: ./ms-consultas
    container_name: hospital-ms-consultas
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8089:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_consultas?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-proveedores:
    build: ./ms-proveedores
    container_name: hospital-ms-proveedores
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8090:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_proveedores?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network

  ms-laboratorio:
    build: ./ms-laboratorio
    container_name: hospital-ms-laboratorio
    depends_on:
      - db-hospital
      - ms-eureka
    ports:
      - "8091:8080"
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-hospital:3306/db_laboratorio?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iha3gaFBMMzwiee8
    restart: on-failure
    networks:
      - hospital-network