spring.application.name=ms-medicos
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db_medicos
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql