server:
    port: 8090

spring:
    application:
        name: gateway
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: pacientes
                          uri: lb://ms-pacientes
                          predicates:
                            - Path=/api/pacientes/**
                        - id: historial
                          uri: lb://ms-pacientes
                          predicates:
                            - Path=/api/historiales/**

                        - id: medicos
                          uri: lb://ms-medicos
                          predicates:
                            - Path=/api/medicos/**
                        - id: especialidad                         
                          uri: lb://ms-medicos
                          predicates:
                            - Path=/api/especialidades/**
                        
                        - id: consultas
                          uri: lb://ms-consultas
                          predicates:
                            - Path=/api/consultas/**

                        - id: citamedica
                          uri: lb://ms-citamedica
                          predicates:
                            - Path=/api/citas/**
                        - id: citamedica
                          uri: lb://ms-citamedica
                          predicates:
                            - Path=/api/salas/**


                        - id: laboratorio
                          uri: lb://ms-laboratorio
                          predicates:
                            - Path=/api/examenes/**
                        - id: laboratorio
                          uri: lb://ms-laboratorio
                          predicates:
                            - Path=/api/ordenes/**

                        - id: inventario
                          uri: lb://ms-inventario
                          predicates:
                            - Path=/api/productos/**
                        - id: inventario
                          uri: lb://ms-laboratorio
                          predicates:
                            - Path=/api/movimientos/**
                        
                        - id: historial
                          uri: lb://ms-historial
                          predicates:
                            - Path=/api/historiales/**
                        - id: historial
                          uri: lb://ms-historial
                          predicates:
                            - Path=/api/registros/**

                        - id: proveedores
                          uri: lb://ms-proveedores
                          predicates:
                            - Path=/api/proveedores/**
                        - id: proveedores
                          uri: lb://ms-proveedores
                          predicates:
                            -Path=/api/ordenes-compra/**

                        - id: facturacion
                          uri: lb://ms-facturacion
                          predicates:
                            - Path=/api/facturas/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        instance:
            prefer-ip-address: true