spring.application.name=ms-auth

server.port= 8091

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#
spring.datasource.url=jdbc:mysql://localhost:3306/db_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=VGhpcy1Jcy1BLVZlcnktU2VjdXJlLVNlY3JldC1LZXktRm9yLUpXVC1BcGktQXV0aGVudGljYXRpb24=
jwt.expiration=86400000

#Configuración de logs
logging.level.com.microservicio_auth.ms_auth=INFO
logging.level.org.springframework.security=INFO